Add default name to config
OakLoaf/Followers pull request #3
Opened 2024-12-31 19:54 UTC by Noogear

2024-12-31 20:04 UTC, OakLoaf requested changes

2024-12-31 20:04 UTC, OakLoaf commented on src/main/java/org/lushplugins/followers/config/ConfigManager.java
> +    private String defaultName;
```suggestion
    private String defaultNickname;
```

2024-12-31 20:04 UTC, OakLoaf commented on src/main/java/org/lushplugins/followers/config/ConfigManager.java
> +        defaultName = config.getString("follower-default-name", "Unnamed");
```suggestion
        defaultNickname = config.getString("follower-default-nickname", "Unnamed");
```

2024-12-31 20:04 UTC, OakLoaf commented on src/main/java/org/lushplugins/followers/config/ConfigManager.java
> +    }
```suggestion
    public String getDefaultNickname() {
        return defaultNickname;
    }
```

2024-12-31 20:04 UTC, OakLoaf commented on src/main/java/org/lushplugins/followers/storage/MysqlStorage.java
> +                FollowerUser newFollowerUser = new FollowerUser(uuid, Bukkit.getPlayer(uuid).getName(), "none", Followers.getInstance().getConfigManager().getDefaultName(), false, false, false);
```suggestion
                FollowerUser newFollowerUser = new FollowerUser(uuid, Bukkit.getPlayer(uuid).getName(), "none", Followers.getInstance().getConfigManager().getDefaultNickname(), false, false, false);
```

2024-12-31 20:04 UTC, OakLoaf commented on src/main/java/org/lushplugins/followers/storage/YmlStorage.java
> +            configurationSection.set("followerDisplayName", Followers.getInstance().getConfigManager().getDefaultName());
```suggestion
            configurationSection.set("followerDisplayName", Followers.getInstance().getConfigManager().getDefaultNickname());
```

2024-12-31 20:04 UTC, OakLoaf commented on src/main/java/org/lushplugins/followers/storage/YmlStorage.java
> +            FollowerUser followerUser = new FollowerUser(uuid, player.getName(), "none", Followers.getInstance().getConfigManager().getDefaultName(), false, false, false);
```suggestion
            FollowerUser followerUser = new FollowerUser(uuid, player.getName(), "none", Followers.getInstance().getConfigManager().getDefaultNickname(), false, false, false);
```

2024-12-31 20:04 UTC, OakLoaf commented on src/main/resources/config.yml
> +follower-default-name: "Unnamed"
```suggestion
follower-default-nickname: "Unnamed"
```

2025-01-01 21:45 UTC, OakLoaf requested changes

2025-01-01 21:45 UTC, OakLoaf commented on src/main/java/org/lushplugins/followers/config/ConfigManager.java
> +        worldBlacklist = new HashSet<>(config.getStringList("world-blacklist"));
I'm not interested in having this changed in this PR, as this is a very short user configured list it doesn't really make sense to worry about hashing values at all, the value of this change is in my opinion not worthwhile

2025-01-01 21:45 UTC, OakLoaf commented on src/main/java/org/lushplugins/followers/config/ConfigManager.java
> -        return worldBlacklist;
I don't personally see any real benefit in removing access to this list, I'd be open to considering adding a separate `isBlacklistedWorld` method in addition to the original method, but any additional unrelated changes should really be done in a separate PR if the need for them is there

2025-01-02 02:14 UTC, Noogear commented on src/main/java/org/lushplugins/followers/config/ConfigManager.java
> +        worldBlacklist = new HashSet<>(config.getStringList("world-blacklist"));
My benchmark results show that the set has a startup time. It's only slower than the list during the first use. After that, regardless of the number of data items, it's faster than the list. Of course, this modification has nothing to do with the pull request (PR). It's more about my personal usage method. I'll restart and submit a PR.

2025-01-02 02:14 UTC, closed without merging